import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/layout/Header'
import {AppProvider} from "@/components/AppContext";
import { Toaster } from 'react-hot-toast';

const poppins = Poppins({ subsets: ['latin'], weight:['100','200','300','400','500','600','700','800','900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth'>
      <body className={poppins.className}>
        <main className="max-w-4xl mx-auto p-4">
            <AppProvider>
              <Toaster toastOptions={{
                                  // Define default options
                                  className: 'text-sm',
                                  duration: 2000,
                                  style: {
                                    background: '#363636',
                                    color: '#fff',
                                  } 
                                }}  />
              <Header />
              {children}
              <footer className='border-t p-8 mt-16 text-center text-gray-500 text-sm '>
                &copy; 2024 All rights reserved
              </footer>
            </AppProvider>
        </main>
        
        
        </body>
    </html>
  )
}
